### ISSUE TITLE
Why is this template better than the original one?

### ISSUE THREAD

**Issue by ellipticaldoor** [Eiskis/vue-webpack#1]
Just asking

**Comment by Eiskis** [comment]
I agree it makes sense to mention this in the documentation. I'll add a summary and/or a full feature comparison table to the docs.

Thanks for filing the issue.

**Comment by Eiskis** [comment]
I have now added a feature comparison page to the documentation: https://eiskis.gitbooks.io/vue-webpack-docs/overview/comparison.html

The project is not very mature yet so whether or not this template is "better" depends on what your needs are, and I tried to bring this up in the docs as well.

@ellipticaldoor If you feel something is missing or incorrect, feel free to reopen this issue.
